municipios = {
    'OLIVENCA': 'Olivença',
    'PAO DE ACUCAR': 'Pão de Açúcar',
    'PIACABUCU': 'Piaçabuçu',
    'POCO DAS TRINCHEIRAS': 'Poço das Trincheiras',
    'VICOSA': 'Viçosa',
    'SANTO ANTONIO DO ICA': 'Santo Antônio do Içá',
    'SAO PAULO DE OLIVENCA': 'São Paulo de Olivença',
    'CALCOENE': 'Calçoene',
    'ALCOBACA': 'Alcobaça',
    'ANTONIO GONCALVES': 'Antônio Gonçalves',
    'ARACAS': 'Araças',
    'BARRA DO CHOCA': 'Barra do Choça',
    'CABACEIRAS DO PARAGUACU': 'Cabaceiras do Paraguaçu',
    'CAMACARI': 'Camaçari',
    'CANSANCAO': 'Cansanção',
    'CONCEICAO DA FEIRA': 'Conceição da Feira',
    'CONCEICAO DO ALMEIDA': 'Conceição do Almeida',
    'CONCEICAO DO COITE': 'Conceição do Coité',
    'CONCEICAO DO JACUIPE': 'Conceição do Jacuípe',
    'CORACAO DE MARIA': 'Coração de Maria',
    'CURACA': 'Curaçá',
    'IACU': 'Iaçu',
    'ITAGUACU DA BAHIA': 'Itaguaçu da Bahia',
    'ITIRUCU': 'Itiruçu',
    'ITUACU': 'Ituaçu',
    'JIQUIRICA': 'Jiquiriçá',
    'JUCURUCU': 'Jucuruçu',
    'LENCOIS': 'Lençóis',
    'NILO PECANHA': 'Nilo Peçanha',
    'NOVA REDENCAO': 'Nova Redenção',
    'NOVA VICOSA': 'Nova Viçosa',
    'OURICANGAS': 'Ouriçangas',
    'PINDOBACU': 'Pindobaçu',
    'POCOES': 'Poções',
    'SAO GONCALO DOS CAMPOS': 'São Gonçalo dos Campos',
    'SAPEACU': 'Sapeaçu',
    'TANHACU': 'Tanhaçu',
    'URUCUCA': 'Uruçuca',
    'VALENCA': 'Valença',
    'VARZEA DA ROCA': 'Várzea da Roça',
    'VARZEA DO POCO': 'Várzea do Poço',
    'CARIRIACU': 'Caririaçu',
    'GRACA': 'Graça',
    'IRAUCUBA': 'Irauçuba',
    'ITAICABA': 'Itaiçaba',
    'MOMBACA': 'Mombaça',
    'REDENCAO': 'Redenção',
    'SAO GONCALO DO AMARANTE': 'São Gonçalo do Amarante',
    'TEJUCUOCA': 'Tejuçuoca',
    'VICOSA DO CEARA': 'Viçosa do Ceará',
    'BOA ESPERANCA': 'Boa Esperança',
    'CONCEICAO DA BARRA': 'Conceição da Barra',
    'CONCEICAO DO CASTELO': 'Conceição do Castelo',
    'DIVINO DE SAO LOURENCO': 'Divino de São Lourenço',
    'GUACUI': 'Guaçuí',
    'IBIRACU': 'Ibiraçu',
    'ITAGUACU': 'Itaguaçu',
    'SAO JOSE DO CALCADO': 'São José do Calçado',
    'ARACU': 'Araçu',
    'ARAGARCAS': 'Aragarças',
    'CACU': 'Caçu',
    'CAMPINACU': 'Campinaçu',
    'ITAUCU': 'Itauçu',
    'MINACU': 'Minaçu',
    'NOVA IGUACU DE GOIAS': 'Nova Iguaçu de Goiás',
    "SAO JOAO D'ALIANCA": "São João d'Aliança",
    'URUACU': 'Uruaçu',
    'ACAILANDIA': 'Açailândia',
    'APICUM-ACU': 'Apicum-Açu',
    'CONCEICAO DO LAGO-ACU': 'Conceição do Lago-Açu',
    'GONCALVES DIAS': 'Gonçalves Dias',
    'GRACA ARANHA': 'Graça Aranha',
    'MARACACUME': 'Maracaçumé',
    'MONCAO': 'Monção',
    'PACO DO LUMIAR': 'Paço do Lumiar',
    'POCAO DE PEDRAS': 'Poção de Pedras',
    'TURIACU': 'Turiaçu',
    'ACUCENA': 'Açucena',
    'ARACAI': 'Araçaí',
    'ARACUAI': 'Araçuaí',
    'BOA ESPERANCA': 'Boa Esperança',
    'CAREACU': 'Careaçu',
    'CLARO DOS POCOS': 'Claro dos Poções',
    'CONCEICAO DA APARECIDA': 'Conceição da Aparecida',
    'CONCEICAO DA BARRA DE MINAS': 'Conceição da Barra de Minas',
    'CONCEICAO DAS ALAGOAS': 'Conceição das Alagoas',
    'CONCEICAO DAS PEDRAS': 'Conceição das Pedras',
    'CONCEICAO DE IPANEMA': 'Conceição de Ipanema',
    'CONCEICAO DO MATO DENTRO': 'Conceição do Mato Dentro',
    'CONCEICAO DO PARA': 'Conceição do Pará',
    'CONCEICAO DO RIO VERDE': 'Conceição do Rio Verde',
    'CONCEICAO DOS OUROS': 'Conceição dos Ouros',
    'CONSOLACAO': 'Consolação',
    'CORACAO DE JESUS': 'Coração de Jesus',
    'DOM VICOSO': 'Dom Viçoso',
    'GONCALVES': 'Gonçalves',
    'IPIACU': 'Ipiaçu',
    'ITATIAIUCU': 'Itatiaiuçu',
    'JAGUARACU': 'Jaguaraçu',
    'JOSE GONCALVES DE MINAS': 'José Gonçalves de Minas',
    'MANHUACU': 'Manhuaçu',
    'MORRO DA GARCA': 'Morro da Garça',
    'ONCA DE PITANGUI': 'Onça de Pitangui',
    'PARAGUACU': 'Paraguaçu',
    'PECANHA': 'Peçanha',
    'PIRANGUCU': 'Piranguçu',
    'POCO FUNDO': 'Poço Fundo',
    'POCOS DE CALDAS': 'Poços de Caldas',
    'SANTA MARIA DO SUACUI': 'Santa Maria do Suaçuí',
    'SANTANA DO MANHUACU': 'Santana do Manhuaçu',
    'SAO BRAS DO SUACUI': 'São Brás do Suaçuí',
    'SAO GONCALO DO ABAETE': 'São Gonçalo do Abaeté',
    'SAO GONCALO DO PARA': 'São Gonçalo do Pará',
    'SAO GONCALO DO RIO ABAIXO': 'São Gonçalo do Rio Abaixo',
    'SAO GONCALO DO RIO PRETO': 'São Gonçalo do Rio Preto',
    'SAO GONCALO DO SAPUCAI': 'São Gonçalo do Sapucaí',
    'SAO JOAO DO MANHUACU': 'São João do Manhuaçu',
    'SAO LOURENCO': 'São Lourenço',
    'SAO PEDRO DO SUACUI': 'São Pedro do Suaçuí',
    'SENADOR MODESTINO GONCALVES': 'Senador Modestino Gonçalves',
    'TAQUARACU DE MINAS': 'Taquaraçu de Minas',
    'TRES CORACOES': 'Três Corações',
    'VICOSA': 'Viçosa',
    'ALTO GARCAS': 'Alto Garças',
    'BARAO DE MELGACO': 'Barão de Melgaço',
    'BARRA DO GARCAS': 'Barra do Garças',
    'COTRIGUACU': 'Cotriguaçu',
    'RESERVA DO CABACAL': 'Reserva do Cabaçal',
    'CAICARA': 'Caiçara',
    'BRAGANCA': 'Bragança',
    'CAPITAO POCO': 'Capitão Poço',
    'CONCEICAO DO ARAGUAIA': 'Conceição do Araguaia',
    'CURUCA': 'Curuçá',
    'IGARAPE-ACU': 'Igarapé-Açu',
    'MELGACO': 'Melgaço',
    'NOVA ESPERANCA DO PIRIA': 'Nova Esperança do Piriá',
    'PICARRA': 'Piçarra',
    'REDENCAO': 'Redenção',
    'TOME-ACU': 'Tomé-Açu',
    'ARACAGI': 'Araçagi',
    'ASSUNCAO': 'Assunção',
    'BAIA DA TRAICAO': 'Baía da Traição',
    'CAICARA': 'Caiçara',
    'CONCEICAO': 'Conceição',
    'ESPERANCA': 'Esperança',
    'MARCACAO': 'Marcação',
    'POCO DANTAS': 'Poço Dantas',
    'POCO DE JOSE DE MOURA': 'Poço de José de Moura',
    'RIACHAO DO POCO': 'Riachão do Poço',
    'SAO SEBASTIAO DE LAGOA DE ROCA': 'São Sebastião de Lagoa de Roça',
    'ALIENCA': 'Aliança',
    'ARACOIABA': 'Araçoiaba',
    'CALCADO': 'Calçado',
    'POCAO': 'Poção',
    'SAO LOURENCO DA MATA': 'São Lourenço da Mata',
    'ASSUNCAO DO PIAUI': 'Assunção do Piauí',
    'CONCEICAO DO CANINDE': 'Conceição do Canindé',
    'MORRO CABECA NO TEMPO': 'Morro Cabeça no Tempo',
    'REDENCAO DO GURGUEIA': 'Redenção do Gurguéia',
    'REGENERACAO': 'Regeneração',
    'RIBEIRO GONCALVES': 'Ribeiro Gonçalves',
    'SAO GONCALO DO GURGUEIA': 'São Gonçalo do Gurguéia',
    'SAO GONCALO DO PIAUI': 'São Gonçalo do Piauí',
    'SAO LOURENCO DO PIAUI': 'São Lourenço do Piauí',
    'URUCU': 'Uruçuí',
    'VALENCA DO PIAUI': 'Valença do Piauí',
    'BOA ESPERANCA': 'Boa Esperança',
    'BOA ESPERANCA DO IGUACU': 'Boa Esperança do Iguaçu',
    'CRUZEIRO DO IGUACU': 'Cruzeiro do Iguaçu',
    'ESPERANCA NOVA': 'Esperança Nova',
    'ESPIGAO ALTO DO IGUACU': 'Espigão Alto do Iguaçu',
    'FOZ DO IGUACU': 'Foz do Iguaçu',
    'GUAIRACA': 'Guairaçá',
    'GUARANIACU': 'Guaraniaçu',
    'GUARAQUECABA': 'Guaraqueçaba',
    'IGUARACU': 'Iguaraçu',
    'ITAPERUCU': 'Itaperuçu',
    'MANDAGUACU': 'Mandaguaçu',
    'NOSSA SENHORA DAS GRACAS': 'Nossa Senhora das Graças',
    'NOVA ALIANCA DO IVAI': 'Nova Aliança do Ivaí',
    'NOVA ESPERANCA': 'Nova Esperança',
    'NOVA ESPERANCA DO SUDOESTE': 'Nova Esperança do Sudoeste',
    'NOVA PRATA DO IGUACU': 'Nova Prata do Iguaçu',
    'PAICANDU': 'Paiçandu',
    'QUEDAS DO IGUACU': 'Quedas do Iguaçu',
    'REBOUCAS': 'Rebouças',
    'RENASCENCA': 'Renascença',
    'RESERVA DO IGUACU': 'Reserva do Iguaçu',
    'RIO BONITO DO IGUACU': 'Rio Bonito do Iguaçu',
    'SAO MIGUEL DO IGUACU': 'São Miguel do Iguaçu',
    'SAO PEDRO DO IGUACU': 'São Pedro do Iguaçu',
    'SAUDADE DO IGUACU': 'Saudade do Iguaçu',
    'SERRANOPOLIS DO IGUACU': 'Serranópolis do Iguaçu',
    'ARMACAO DOS BUZIOS': 'Armação dos Búzios',
    'CONCEICAO DE MACABU': 'Conceição de Macabu',
    'NOVA IGUACU': 'Nova Iguaçu',
    'SAO GONCALO': 'São Gonçalo',
    'VALENCA': 'Valença',
    'ACU': 'Açu',
    'CAICARA DO NORTE': 'Caiçara do Norte',
    'CAICARA DO RIO DO VENTO': 'Caiçara do Rio do Vento',
    'IPANGUACU': 'Ipanguaçu',
    'JACANA': 'Jaçanã',
    'POCO BRANCO': 'Poço Branco',
    'SAO GONCALO DO AMARANTE': 'São Gonçalo do Amarante',
    'VICOSA': 'Viçosa',
    'BENTO GONCALVES': 'Bento Gonçalves',
    'CACAPAVA DO SUL': 'Caçapava do Sul',
    'CAICARA': 'Caiçara',
    'CANGUCU': 'Canguçu',
    'ESPERANCA DO SUL': 'Esperança do Sul',
    'ESTACAO': 'Estação',
    'IBIACA': 'Ibiaçá',
    'MACAMBARA': 'Maçambará',
    'MORMACO': 'Mormaço',
    'MUCUM': 'Muçum',
    'NOVA ARACA': 'Nova Araçá',
    'NOVA ESPERANCA DO SUL': 'Nova Esperança do Sul',
    'PEJUCARA': 'Pejuçara',
    'POCO DAS ANTAS': 'Poço das Antas',
    'SAO LOURENCO DO SUL': 'São Lourenço do Sul',
    'TAQUARUCU DO SUL': 'Taquaruçu do Sul',
    'TURUCU': 'Turuçu',
    'BALNEARIO PISCARRAS': 'Balneário Piçarras',
    'BIGUACU': 'Biguaçu',
    'BRACO DO NORTE': 'Braço do Norte',
    'BRACO DO TROMBUDO': 'Braço do Trombudo',
    'CACADOR': 'Caçador',
    'ICARA': 'Içara',
    'IPUACU': 'Ipuaçu',
    'JOACABA': 'Joaçaba',
    'MORRO DA FUMACA': 'Morro da Fumaça',
    'PALHOCA': 'Palhoça',
    'SAO LOURENCO DO OESTE': 'São Lourenço do Oeste',
    'POCO REDONDO': 'Poço Redondo',
    'POCO VERDE': 'Poço Verde',
    'ARACARIGUAMA': 'Araçariguama',
    'ARACATUBA': 'Araçatuba',
    'ARACOIABA DA SERRA': 'Araçoiaba da Serra',
    'BOA ESPERANCA DO SUL': 'Boa Esperança do Sul',
    'BRAGANCA PAULISTA': 'Bragança Paulista',
    'CACAPAVA': 'Caçapava',
    'EMBU-GUACU': 'Embu-Guaçu',
    'GARCA': 'Garça',
    'GUAICARA': 'Guaiçara',
    'GUAPIACU': 'Guapiaçu',
    'GUARACAI': 'Guaraçaí',
    'IGARACU DO TIETE': 'Igaraçu do Tietê',
    'LENCOIS PAULISTA': 'Lençóis Paulista',
    'MENDONCA': 'Mendonça',
    'MOGI GUACU': 'Mogi Guaçu',
    'MONCOES': 'Monções',
    'NOVA ALIANCA': 'Nova Aliança',
    'OCAUCU': 'Ocauçu',
    'PARAGUACU PAULISTA': 'Paraguaçu Paulista',
    'PARIQUERA-ACU': 'Pariquera-Açu',
    'REDENCAO DA SERRA': 'Redenção da Serra',
    'SANTA CRUZ DA CONCEICAO': 'Santa Cruz da Conceição',
    'SANTA CRUZ DA ESPERANCA': 'Santa Cruz da Esperança',
    'SAO LOURENCO DA SERRA': 'São Lourenço da Serra',
    'TAIACU': 'Taiaçu',
    'ALIENCA DO TOCANTINS': 'Aliança do Tocantins',
    'ARAGUACU': 'Araguaçu',
    'BABACULANDIA': 'Babaçulândia',
    'CONCEICAO DO TOCANTINS': 'Conceição do Tocantins',
    'RIO DA CONCEICAO': 'Rio da Conceição'
}
